remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

logo: assets/photo.jpg
title: Yuchao Qin
description: Yuchao's personal webpage
show_downloads: false

github:
  - is_user_page: true
