remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

logo: assets/photo_small.jpg
title: Yuchao Qin
description: Yuchao's personal webpage
show_downloads: false

github:
  is_user_page: true
  is_project_page: false
  owner_url: https://github.com/yvchao
